# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sime1.dev
email: sime.pizzi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Simeone. I'm an italian developer based in Padua.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sime1.dev" # the base hostname & protocol for your site, e.g. http://example.com
social:
- name: twitter
  username: sime1dev
- name: github
  username: sime1
- name: linkedin
  username: sime1
  base_url: http://www.linkedin.com/in/
- name: email
  username: info@sime1.dev
  base_url: "mailto:"
  icon_family: far
  icon: envelope

twitter_username: sime1dev
github_username:  sime1
linkedin_username: sime1

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
header_pages:
- about.md
- resume.md
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
